sudo: required
services:
  - docker
before_install:
  - docker build -t hitos/docker-eureka -f Dockerfile .
script:
  - docker run hitos/docker-eureka
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-training"
  env: "DockerTraining-env"
  bucket_name: "elasticbeanstalk-us-east-2-043463385668"
  bucket_path: "docker-training"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"